import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, ImagePlus } from "lucide-react";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/add-dog")({ head: () => ({ meta: [{ title: "Añadir perro — Patitas Club" }, { name: "description", content: "Crea el perfil de tu perro y preséntalo a la comunidad de Patitas Club." }, { property: "og:title", content: "Presenta a tu mejor amigo" }, { property: "og:description", content: "Añade a tu perro a Patitas Club." }] }), component: AddDogPage });

function AddDogPage() {
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!["name", "breed", "age", "personality", "owner"].every((key) => String(form.get(key) ?? "").trim())) { setError("Completa los campos marcados para presentar a tu perro."); return; } setError(""); setSuccess(true); }
  if (success) return <div className="mx-auto grid min-h-[65vh] max-w-xl place-items-center px-5 text-center"><div><CheckCircle2 className="mx-auto size-16 text-accent"/><h1 className="mt-5 text-4xl font-extrabold">¡Qué alegría conocerle!</h1><p className="mt-3 text-lg text-muted-foreground">El perfil quedó listo para revisión. Te avisaremos cuando aparezca en la comunidad.</p><Button asChild variant="warm" className="mt-7"><Link to="/dogs">Explorar perros</Link></Button></div></div>;
  return <div className="mx-auto max-w-3xl px-5 py-14 lg:px-8"><p className="font-bold text-primary">NUEVO PERFIL</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">Presenta a tu mejor amigo</h1><p className="mt-4 text-lg text-muted-foreground">Cuéntanos eso que hace que tu perro sea tan especial. Los perfiles se revisan para mantener una comunidad amable y segura.</p><div className="mt-9 rounded-3xl bg-card p-6 shadow-warm sm:p-9"><div className="mb-8 rounded-2xl border border-dashed border-border bg-muted/50 p-8 text-center"><ImagePlus className="mx-auto size-9 text-primary"/><p className="mt-3 font-bold">Añade una foto bonita</p><p className="mt-1 text-sm text-muted-foreground">La subida de fotos estará disponible al iniciar sesión.</p></div><form onSubmit={submit} noValidate className="grid gap-6 sm:grid-cols-2">{[{name:"name",label:"Nombre *",placeholder:"Luna"},{name:"breed",label:"Raza *",placeholder:"Golden Retriever"},{name:"age",label:"Edad *",placeholder:"4 años"},{name:"owner",label:"Tu nombre *",placeholder:"Ana"}].map((field)=><label key={field.name} className="grid gap-2 font-semibold">{field.label}<Input name={field.name} maxLength={field.name === "age" ? 40 : 100} placeholder={field.placeholder} className="h-12 rounded-xl"/></label>)}<label className="grid gap-2 font-semibold sm:col-span-2">Personalidad *<Input name="personality" maxLength={240} placeholder="Sociable, tranquila y loca por las pelotas" className="h-12 rounded-xl"/></label><label className="grid gap-2 font-semibold sm:col-span-2">Notas<Textarea name="notes" maxLength={1200} placeholder="Sus paseos favoritos, pequeñas manías o cualquier cosa que quieras compartir…" className="min-h-28 rounded-xl"/></label>{error && <p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive sm:col-span-2">{error}</p>}<div className="flex flex-wrap items-center justify-between gap-4 sm:col-span-2"><p className="text-sm text-muted-foreground">Necesitarás iniciar sesión para publicar.</p><Button type="submit" variant="warm" size="lg">Añadir perro</Button></div></form></div></div>;
}