import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Tu cuenta — Patitas Club" }, { name: "description", content: "Inicia sesión o crea una cuenta para añadir y gestionar los perfiles de tus perros." }] }), component: AuthPage });

function AuthPage() {
  const navigate = useNavigate();
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [message, setMessage] = useState("");
  const [pending, setPending] = useState(false);
  async function handleEmail(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const email = String(form.get("email") ?? "").trim(); const password = String(form.get("password") ?? ""); if (!email.includes("@") || password.length < 8) { setMessage("Escribe un correo válido y una contraseña de al menos 8 caracteres."); setPending(false); return; } const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }); setPending(false); if (result.error) { setMessage("No pudimos completar el acceso. Revisa tus datos e inténtalo otra vez."); return; } if (mode === "signup") { setMessage("Revisa tu correo para confirmar la cuenta. ¡Ya casi estás dentro!"); } else { navigate({ to: "/dogs" }); } }
  async function handleGoogle() { setPending(true); const { lovable } = await import("@/integrations/lovable"); const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: window.location.origin }); if (result.error) { setMessage("Google no pudo completar el acceso. Inténtalo de nuevo."); setPending(false); return; } if (!result.redirected) navigate({ to: "/dogs" }); }
  return <div className="mx-auto grid min-h-[70vh] max-w-7xl items-center gap-12 px-5 py-14 lg:grid-cols-2 lg:px-8"><div><span className="text-6xl" aria-hidden="true">🐕</span><h1 className="mt-5 text-4xl font-extrabold sm:text-5xl">Tu rincón en la comunidad</h1><p className="mt-4 max-w-lg text-lg leading-8 text-muted-foreground">Guarda el perfil de tu perro, actualiza sus historias y forma parte de una comunidad que comparte el mismo cariño.</p></div><div className="rounded-3xl bg-card p-7 shadow-warm sm:p-9"><div className="mb-7 grid grid-cols-2 rounded-full bg-muted p-1"><button type="button" onClick={() => { setMode("login"); setMessage(""); }} className={`rounded-full px-4 py-2.5 text-sm font-bold ${mode === "login" ? "bg-card shadow-sm" : "text-muted-foreground"}`}>Entrar</button><button type="button" onClick={() => { setMode("signup"); setMessage(""); }} className={`rounded-full px-4 py-2.5 text-sm font-bold ${mode === "signup" ? "bg-card shadow-sm" : "text-muted-foreground"}`}>Crear cuenta</button></div><Button type="button" variant="outline" size="lg" className="w-full rounded-full" onClick={handleGoogle} disabled={pending}>Continuar con Google</Button><div className="my-6 flex items-center gap-3 text-xs font-bold text-muted-foreground"><span className="h-px flex-1 bg-border"/> O CON CORREO <span className="h-px flex-1 bg-border"/></div><form onSubmit={handleEmail} className="grid gap-5"><label className="grid gap-2 font-semibold">Correo electrónico<Input type="email" name="email" autoComplete="email" maxLength={255} className="h-12 rounded-xl"/></label><label className="grid gap-2 font-semibold">Contraseña<Input type="password" name="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={8} maxLength={72} className="h-12 rounded-xl"/></label>{message && <p role="status" className="rounded-xl bg-secondary p-3 text-sm font-semibold">{message}</p>}<Button type="submit" variant="warm" size="lg" disabled={pending}>{pending ? "Un momento…" : mode === "login" ? "Entrar a Patitas Club" : "Crear mi cuenta"}</Button></form></div></div>;
}